const data = {
  products: [
    {
      //_id: '1',
      name: 'Nike shirt',
      slug: 'nike-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg', //679*829
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 10,
      description: 'thicc shirt',
    },
    {
      //_id: '2',
      name: 'Nike pant',
      slug: 'nike-pant',
      category: 'Pants',
      image: '/images/p2.jpg',
      price: 120,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 10,
      description: 'thicc pants',
    },
    {
      //_id: '3',
      name: 'Adidas shirt',
      slug: 'adidas-shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.4,
      numReviews: 10,
      description: 'thicc shirts',
    },
    {
      //_id: '4',
      name: 'Adidas pant',
      slug: 'adidas-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.4,
      numReviews: 10,
      description: 'thicc pants',
    },
  ],
};
export default data;
